"""init schema

Revision ID: 3d5bc03b570d
Revises: 
Create Date: 2026-07-20 20:13:48.062881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5bc03b570d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_key', sa.String(length=64), nullable=False),
    sa.Column('channel_code', sa.String(length=8), nullable=False),
    sa.Column('order_throughput', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('load_percentage', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_readings_channel_code'), 'signal_readings', ['channel_code'], unique=False)
    op.create_index(op.f('ix_signal_readings_recorded_at'), 'signal_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_signal_readings_signal_key'), 'signal_readings', ['signal_key'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_signal_readings_signal_key'), table_name='signal_readings')
    op.drop_index(op.f('ix_signal_readings_recorded_at'), table_name='signal_readings')
    op.drop_index(op.f('ix_signal_readings_channel_code'), table_name='signal_readings')
    op.drop_table('signal_readings')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
